require 'rubygems'
require 'builder'
require 'logger'

#
# The FusionCharts module contains the classes used for emitting the XML to
# define graphs and charts to be generated by FusionCharts
#
module FusionCharts

  # A collection of DataPoints to be graphed
  class DataSet
    @@PRIMARY_AXIS = "P"
    @@SECONDARY_AXIS = "S"
    
    attr_accessor :alpha, :anchorAlpha, :anchorBackgroundAlpha, :anchorBackgroundColor,
                  :anchorBorderColor, :anchorBorderThickness, :anchorRadius,
                  :anchorSides, :color, :dataPoints, :lineThickness, :numberPrefix,
                  :parentYAxis, :seriesName, :showAnchors, :showValues
    
    def initialize
      dataPoints = []
    end

    def to_xml     
      result = String.new
      builder = Builder::XmlMarkup.new(:target => result, :indent => 2)
  
      attributes = {}
      instance_variables.each do |iv|
        attributes[iv.split("@")[1]] = normalize instance_variable_get(iv)
      end
      
      attributes.reject! do |k,v| attributes_to_reject.include? k end

      builder.tag!("dataset", attributes) do
        dataPoints.each do |dp|
          builder << dp.to_xml
        end
      end
      
      result
    end
  
    def normalize(value)
      return "1" if value.class == TrueClass
      return "0" if value.class == FalseClass
      return value
    end

    private

    def attributes_to_reject
      %w{ dataPoints }
    end
  end

end
