require 'rubygems'
require 'builder'
require 'logger'

#
# The FusionCharts module contains the classes used for emitting the XML to
# define graphs and charts to be generated by FusionCharts
#
module FusionCharts

  # A chart that includes categories, datasets, and trendlines
  class MultiSeriesChart < Base
    attr_accessor :categories, :dataSets, :trendLines
    
    def initialize
      categories = []
      dataSets = []
      trendLines = []
    end
    
    def to_xml
      inner = String.new
      inner_builder = Builder::XmlMarkup.new(:target => inner, :indent => 2)
  
      # create the XML for the inner "categories" element(s)
      inner_builder.tag!("categories") do
        categories.each do |category|
          inner_builder << category.to_xml
        end
      end
      
      # create the XML for the inner "dataset" element(s)
      dataSets.each do |dataset|
        inner_builder << dataset.to_xml
      end
      
      # create the XML for the inner "trendLines" element(s)
      inner_builder.tag!("trendLines") do
        trendLines.each do |trendLine|
          inner_builder << trendLine.to_xml
        end
      end
      
      # create the XML for this chart, including attributes defined in the Base chart type
      # but not including the attributes for this chart type
      result = super(nil, inner)
      
      result
    end
  end

end